"""UI translation strings for the BelVoice testing web UI."""

from typing import Any, Dict, List, Tuple

UI_LANGUAGES: List[Tuple[str, str]] = [
    ("be", "BY"),
    ("en", "EN"),
]

_BASE: Dict[str, str] = {
    "brand_title": "BelVoice",
    "brand_sub": "Тэставы UI",
    "menu": "Меню",
    "home": "Галоўная",
    "home_sub": "Абярыце рэжым і апрацуйце тэкст або аўдыя.",
    "pipeline": "Пайплайн",
    "settings": "Налады",
    "open_menu": "Адкрыць меню",
    "sidebar": "Бакавое меню",
    "main_nav": "Галоўная навігацыя",
    "breadcrumbs": "Хлебныя крошкі",
    "search": "Пошук",
    "open_command_palette": "Адкрыць камандную панэль",
    "command_palette_input": "Увод каманднай панэлі",
    "command_palette": "Камандная панэль",
    "no_matching_commands": "Няма супадзенняў",
    "cp_placeholder": "Увядзіце каманду ці перайдзіце па раздзеле...",
    "toggle_day_night": "Пераключыць дзень/ноч",
    "toggle_modern_simple": "Пераключыць стыль modern/simple",
    "choose_accent_color": "Абраць акцэнтны колер",
    "accent_lime": "Лайм",
    "accent_coral": "Каралавы",
    "accent_purple": "Фіялетавы",
    "accent_blue": "Блакітны",
    "accent_amber": "Бурштынавы",
    "accent_pink": "Ружовы",
    "accent_teal": "Бірузовы",
    "ui_language": "Мова інтэрфейсу",
    "error": "Памылка",
    "done": "Гатова",
    "continue": "Працягнуць",
    "retry": "Паўтарыць",
    "processing": "Апрацоўка",
    "please_wait": "Калі ласка, пачакайце",
    "save_settings": "Захаваць налады",
    "settings_saved": "Налады захаваны",
    "result": "Вынік",
    "result_for": "Вынік ({mode})",
    "mode": "Рэжым",
    "mode_sub": "Абярыце рэжым апрацоўкі.",
    "config_providers": "Канфігурацыя правайдэраў",
    "config_providers_sub": "Ключы API і налады мадэляў для вонкавых правайдэраў.",
    "tts_pipeline": "TTS-пайплайн",
    "tts_pipeline_sub": "Абярыце правайдэраў для кожнага этапу сінтэзу.",
    "asr": "Распазнаванне маўлення (ASR)",
    "asr_provider": "Правайдэр ASR",
    "normalization": "Нармалізацыя",
    "stress": "Націскі",
    "phonemization": "Фанемізацыя",
    "input": "Уваход",
    "input_sub": "Увядзіце тэкст або запампуйце аўдыя.",
    "text": "Тэкст",
    "text_placeholder": "Прывітанне, свет!",
    "audio_file": "Аўдыяфайл",
    "run": "Запусціць",
    "file": "Файл",
    "steps": "Крокі",
    "api_key": "API key",
    "api_key_optional": "API key (неабавязкова)",
    "chat_model": "Chat-мадэль",
    "tts_model": "TTS-мадэль",
    "model": "Мадэль",
    "base_url": "Base URL",
    "whisper_model": "Whisper-мадэль",
    "opt_none": "Няма",
    "opt_simple": "Simple (лагічныя правілы)",
    "opt_stat": "Stat (слоўнікі)",
    "opt_belg2p": "BelG2P (Java)",
    "opt_coqui": "CoquiTTS (лагчаны)",
    "opt_omnivoice": "OmniVoice (GPU)",
    "opt_mistral": "Mistral",
    "opt_openrouter": "OpenRouter",
    "opt_lmstudio": "LMStudio",
    "opt_gemini": "Gemini",
    "hint_phonemization": "CoquiTTS найлепш працуе з фанемамі.",
    "command_home": "Галоўная",
    "command_tts": "Рэжым: TTS-пайплайн",
    "command_asr": "Рэжым: ASR",
    "command_normalization": "Рэжым: Нармалізацыя",
    "command_stress": "Рэжым: Націскі",
    "command_phonemization": "Рэжым: Фанемізацыя",
    "command_settings": "Налады",
}

_TRANSLATIONS: Dict[str, Dict[str, str]] = {
    "be": _BASE,
    "en": {
        "brand_sub": "Testing UI",
        "menu": "Menu",
        "home": "Home",
        "home_sub": "Choose a mode and process text or audio.",
        "pipeline": "Pipeline",
        "settings": "Settings",
        "open_menu": "Open menu",
        "sidebar": "Sidebar",
        "main_nav": "Main navigation",
        "breadcrumbs": "Breadcrumbs",
        "search": "Search",
        "open_command_palette": "Open command palette",
        "command_palette_input": "Command palette input",
        "command_palette": "Command palette",
        "no_matching_commands": "No matching commands",
        "cp_placeholder": "Type a command or navigate to a section...",
        "toggle_day_night": "Toggle day/night",
        "toggle_modern_simple": "Toggle modern/simple style",
        "choose_accent_color": "Choose accent color",
        "accent_lime": "Lime",
        "accent_coral": "Coral",
        "accent_purple": "Purple",
        "accent_blue": "Blue",
        "accent_amber": "Amber",
        "accent_pink": "Pink",
        "accent_teal": "Teal",
        "ui_language": "Interface language",
        "error": "Error",
        "done": "Done",
        "continue": "Continue",
        "retry": "Retry",
        "processing": "Processing",
        "please_wait": "Please wait",
        "save_settings": "Save settings",
        "settings_saved": "Settings saved",
        "result": "Result",
        "result_for": "Result ({mode})",
        "mode": "Mode",
        "mode_sub": "Choose the processing mode.",
        "config_providers": "Provider configuration",
        "config_providers_sub": "API keys and model settings for external providers.",
        "tts_pipeline": "TTS pipeline",
        "tts_pipeline_sub": "Choose providers for each synthesis stage.",
        "asr": "Speech recognition (ASR)",
        "asr_provider": "ASR provider",
        "normalization": "Normalization",
        "stress": "Stress",
        "phonemization": "Phonemization",
        "input": "Input",
        "input_sub": "Enter text or upload audio.",
        "text": "Text",
        "text_placeholder": "Hello, world!",
        "audio_file": "Audio file",
        "run": "Run",
        "file": "File",
        "steps": "Steps",
        "api_key": "API key",
        "api_key_optional": "API key (optional)",
        "chat_model": "Chat model",
        "tts_model": "TTS model",
        "model": "Model",
        "base_url": "Base URL",
        "whisper_model": "Whisper model",
        "opt_none": "None",
        "opt_simple": "Simple (rule-based)",
        "opt_stat": "Stat (dictionaries)",
        "opt_belg2p": "BelG2P (Java)",
        "opt_coqui": "CoquiTTS (local)",
        "opt_omnivoice": "OmniVoice (GPU)",
        "opt_mistral": "Mistral",
        "opt_openrouter": "OpenRouter",
        "opt_lmstudio": "LMStudio",
        "opt_gemini": "Gemini",
        "hint_phonemization": "CoquiTTS works best with phonemes.",
        "command_home": "Home",
        "command_tts": "Mode: TTS pipeline",
        "command_asr": "Mode: ASR",
        "command_normalization": "Mode: Normalization",
        "command_stress": "Mode: Stress",
        "command_phonemization": "Mode: Phonemization",
        "command_settings": "Settings",
    },
}


def get_ui_text(lang: str) -> Dict[str, str]:
    """Return UI strings for the requested language, falling back to Belarusian."""
    base: Dict[str, str] = dict(_BASE)
    overrides: Dict[str, str] = _TRANSLATIONS.get(lang, {})
    merged: Dict[str, str] = {**base, **overrides}
    return merged
